version: "3"
networks:
  vteam-rabbitmq:

services:
  db:
    image: mongo
    container_name: "db"
    restart: always
    ports:
      - "27017:27017"
    networks:
      vteam-rabbitmq:
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mq:
    image: rabbitmq
    container_name: "mq"
    restart: always
    ports:
      - "5672:5672"
    networks:
      vteam-rabbitmq:

